import type { UNITS } from '@prisma/client';

export const countries = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe'
];

export const drugDosages: {
	amount: number;
	unit: UNITS;
	per: number;
	perUnit: UNITS;
}[] = [
	{ amount: 1, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 2, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 10, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 20, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 25, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 50, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 75, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 100, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 150, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 200, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 250, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 300, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 400, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 500, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 600, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 750, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 800, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 900, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1000, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 2.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 7.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 12.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 17.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 37.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 62.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 125, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1500, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 180, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 360, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.25, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.75, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1.25, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.1, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.2, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 0.3, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 1.5, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 2, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 3, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 4, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 5, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 6, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 8, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 10, unit: 'g', per: 1, perUnit: 'unit' }
];

export const drugForms = [
	'AEROSOL',
	'BALM',
	'CAPSULE',
	'CREAM',
	'ELIXIR',
	'EMULSION',
	'FOAM',
	'GEL',
	'INHALANT',
	'INJECTION',
	'LIQUID',
	'LOTION',
	'MASK',
	'OIL',
	'OINTMENT',
	'PATCH',
	'PILL',
	'POWDER',
	'SERUM',
	'SOLUTION',
	'SPRAY',
	'SUPPOSITORY',
	'SUSPENSION',
	'SYRUP',
	'TABLET',
	'TINCTURE',
	'TOOTHPASTE',
	'MOUTHWASH',
	'SKIN_CARE',
	'COSMETIC',
	'SHAMPOO',
	'PASTE',
	'GUM',
	'DROPS',
	'PELLET',
	'CAPLET',
	'POULTICE'
];

export const indications = [
	'Pain',
	'Fever',
	'Inflammation',
	'Migraine',
	'Stroke',
	'Heartburn',
	'Nausea',
	'Cough',
	'Cold',
	'Flu',
	'Diarrhea',
	'Constipation',
	'Allergy',
	'Rash',
	'Headache',
	'Dizziness',
	'Fatigue',
	'Insomnia',
	'Anxiety',
	'Depression',
	'Arthritis',
	'Diabetes',
	'Hypertension',
	'Asthma',
	'Bronchitis',
	'Pneumonia',
	'Cancer',
	'Ulcer',
	'Gastritis',
	'Hemorrhoids',
	'Acne',
	'Angina',
	'Anemia',
	'Anorexia',
	'Arrhythmia',
	'Atherosclerosis',
	'Backache',
	'Bleeding',
	'Blisters',
	'Burns',
	'Cholesterol',
	'Colitis',
	'Conjunctivitis',
	'Cramps',
	'Dermatitis',
	'Dyspepsia',
	'Eczema',
	'Edema',
	'Emphysema',
	'Epilepsy',
	'Fibromyalgia',
	'Flatulence',
	'Glaucoma',
	'Gout',
	'Herpes',
	'Hyperthyroidism',
	'Hypothyroidism',
	'Impotence',
	'Infection',
	'Influenza',
	'Itching',
	'Jaundice',
	'Leukemia',
	'Lymphoma',
	'Malaria',
	'Menopause',
	'Menstruation',
	'Myalgia',
	'Neuralgia',
	'Obesity',
	'Osteoporosis',
	'Palpitations',
	'Pancreatitis',
	'Psoriasis',
	'Scabies',
	'Sinusitis',
	'Sneezing',
	'Spasms',
	'Swelling',
	'Syphilis',
	'Tetanus',
	'Thrombosis',
	'Tinnitus',
	'Tuberculosis',
	'Ulceration',
	'Vomiting',
	'Warts',
	'Wheezing',
	'Yeast',
	'Tendonitis',
	'Carpal Tunnel',
	'Restless Leg Syndrome',
	'Rosacea',
	'Gingivitis',
	'Multiple Sclerosis',
	'Parkinson’s Disease',
	'Polymyalgia Rheumatica'
];

export const contraIndications = [
	'Allergy',
	'Pregnancy',
	'Lactation',
	'Hypersensitivity',
	'Anemia',
	'Asthma',
	'Bleeding',
	'Breastfeeding',
	'Cancer',
	'Cardiomyopathy',
	'Cirrhosis',
	'Colitis',
	'Coma',
	'Dehydration',
	'Depression',
	'Diabetes',
	'Diarrhea',
	'Emphysema',
	'Epilepsy',
	'Glaucoma',
	'Gout',
	'Hepatitis',
	'Hypertension',
	'Hypotension',
	'Hyperthyroidism',
	'Hypothyroidism',
	'Infection',
	'Inflammation',
	'Jaundice',
	'Kidney',
	'Liver',
	'Malnutrition',
	'Menopause',
	'Menstruation',
	'Migraine',
	'Myocarditis',
	'Obesity',
	'Osteoporosis',
	'Pancreatitis',
	'Parkinson',
	'Peptic',
	'Psychosis',
	'Seizures',
	'Shock',
	'Stomach',
	'Stroke',
	'Surgery',
	'Thrombosis',
	'Tuberculosis',
	'Ulcer',
	'Vertigo',
	'Vomiting',
	'Cardiac Failure',
	'Arrhythmias',
	'Addison’s Disease',
	'Adrenal Insufficiency',
	'Alcoholism',
	'Aortic Stenosis',
	'Autoimmune Disease'
];

export const activeIngredients = [
	'Aspirin',
	'Ibuprofen',
	'Paracetamol',
	'Amoxicillin',
	'Metformin',
	'Atorvastatin',
	'Omeprazole',
	'Lisinopril',
	'Simvastatin',
	'Levothyroxine',
	'Amlodipine',
	'Metoprolol',
	'Hydrochlorothiazide',
	'Losartan',
	'Gabapentin',
	'Citalopram',
	'Albuterol',
	'Prednisone',
	'Acetaminophen',
	'Ciprofloxacin',
	'Clindamycin',
	'Doxycycline',
	'Furosemide',
	'Hydrocodone',
	'Hydroxychloroquine',
	'Indomethacin',
	'Loratadine',
	'Meloxicam',
	'Methotrexate',
	'Metronidazole',
	'Montelukast',
	'Naproxen',
	'Nifedipine',
	'Ondansetron',
	'Oxycodone',
	'Pantoprazole',
	'Prednisolone',
	'Ranitidine',
	'Sertraline',
	'Sildenafil',
	'Spironolactone',
	'Sumatriptan',
	'Tamsulosin',
	'Tetracycline',
	'Tramadol',
	'Trimethoprim',
	'Valsartan',
	'Venlafaxine',
	'Warfarin',
	'Zolpidem',
	'Acetazolamide',
	'Alendronate',
	'Allopurinol',
	'Azithromycin',
	'Bisoprolol',
	'Budesonide',
	'Carbamazepine',
	'Cefalexin',
	'Cetirizine',
	'Chlorphenamine',
	'Chlorpromazine',
	'Clopidogrel',
	'Codeine',
	'Cyclobenzaprine',
	'Dexamethasone',
	'Diazepam',
	'Digoxin',
	'Diphenhydramine',
	'Duloxetine',
	'Enalapril',
	'Esomeprazole',
	'Fluconazole',
	'Fluoxetine',
	'Folic',
	'Glyburide',
	'Gemfibrozil',
	'Glipizide',
	'Haloperidol',
	'Hydralazine',
	'Hydromorphone',
	'Hydroxyzine',
	'Isosorbide',
	'Ketoconazole',
	'Labetalol',
	'Lamotrigine',
	'Levofloxacin',
	'Lidocaine',
	'Lithium',
	'Loperamide',
	'Methocarbamol',
	'Methylprednisolone',
	'Minocycline',
	'Mirtazapine',
	'Nalbuphine',
	'Nitrofurantoin',
	'Nitroglycerin',
	'Nortriptyline',
	'Olanzapine',
	'Oxcarbazepine',
	'Phenobarbital',
	'Phenytoin',
	'Pioglitazone',
	'Prazosin',
	'Propranolol',
	'Risperidone',
	'Scopolamine',
	'Tizanidine',
	'Tolterodine',
	'Topiramate',
	'Valproate',
	'Verapamil',
	'Metamizole',
	'Rivaroxaban',
	'Clarithromycin',
	'Mometasone',
	'Aciclovir',
	'Brimonidine',
	'Isotretinoin',
	'Apixaban',
	'Fentanyl',
	'Risperidone',
	'Ropinirole'
];

export const drugCategories = [
	{ name: 'Analgesic', description: 'Used to relieve pain.' },
	{ name: 'Antibiotic', description: 'Used to treat bacterial infections.' },
	{ name: 'Antifungal', description: 'Used to treat fungal infections.' },
	{ name: 'Antipyretic', description: 'Used to reduce fever.' },
	{ name: 'Antiseptic', description: 'Used to prevent infection in wounds.' },
	{ name: 'Antidepressant', description: 'Used to treat depression.' },
	{ name: 'Antipsychotic', description: 'Used to manage psychosis, including schizophrenia.' },
	{ name: 'Anticonvulsant', description: 'Used to prevent seizures.' },
	{ name: 'Antihistamine', description: 'Used to relieve allergy symptoms.' },
	{ name: 'Antihypertensive', description: 'Used to lower blood pressure.' },
	{ name: 'Diuretic', description: 'Used to remove excess fluid from the body.' },
	{
		name: 'Bronchodilator',
		description: 'Used to relax muscles of the airways and increase airflow to the lungs.'
	},
	{ name: 'Decongestant', description: 'Used to relieve nasal congestion.' },
	{ name: 'Laxative', description: 'Used to relieve constipation.' },
	{ name: 'Sedative', description: 'Used to induce calmness and sleep.' },
	{ name: 'Stimulant', description: 'Used to increase alertness and energy.' },
	{ name: 'Anti-inflammatory', description: 'Used to reduce inflammation.' },
	{ name: 'Antiemetic', description: 'Used to prevent vomiting.' },
	{ name: 'Anticoagulant', description: 'Used to prevent blood clotting.' },
	{ name: 'Hypnotic', description: 'Used to induce sleep.' },
	{ name: 'Hormone', description: 'Used to replace or supplement naturally occurring hormones.' },
	{ name: 'Vaccine', description: 'Used to provide immunity against various diseases.' },
	{ name: 'Antiviral', description: 'Used to treat viral infections.' },
	{ name: 'Immunosuppressant', description: 'Used to suppress the immune system.' },
	{ name: 'Antidiabetic', description: 'Used to control blood sugar levels in diabetes.' },
	{ name: 'Statin', description: 'Used to lower cholesterol levels.' },
	{ name: 'Muscle Relaxant', description: 'Used to relieve muscle spasms.' },
	{ name: 'Expectorant', description: 'Used to help clear mucus from the airways.' },
	{ name: 'Antispasmodic', description: 'Used to relieve muscle spasms.' },
	{
		name: 'Antiplatelet',
		description: 'Used to prevent blood cells from sticking together and forming a clot.'
	},
	{
		name: 'Corticosteroid',
		description: 'Used to reduce inflammation and suppress the immune system.'
	},
	{ name: 'Antiglaucoma', description: 'Used to treat glaucoma.' },
	{ name: 'Osteoporosis', description: 'Used to treat and prevent osteoporosis.' },
	{ name: 'Gastroprotective', description: 'Used to protect the gastrointestinal tract.' },
	{ name: 'Probiotic', description: 'Used to promote a healthy balance of gut bacteria.' },
	{ name: 'Antiarrhythmic', description: 'Used to treat irregular heartbeats.' },
	{ name: 'Antiparasitic', description: 'Used to treat parasitic infections.' },
	{ name: 'Antithyroid', description: 'Used to treat hyperthyroidism.' },
	{ name: 'Antimalarial', description: 'Used to prevent or treat malaria.' },
	{ name: 'Chemotherapy', description: 'Used to treat cancer.' },
	{
		name: 'Anticholinergic',
		description: 'Used to treat a variety of conditions, including incontinence and COPD.'
	}
];

function checkDuplicates(arr) {
	const seen = new Set();
	for (const item of arr) {
		if (seen.has(item)) {
			console.log(`Duplicate found: ${item}`);
			return true;
		}
		seen.add(item);
	}
	return false;
}
console.log('Checking drugForms:', checkDuplicates(drugForms));
console.log('Checking indications:', checkDuplicates(indications));
console.log('Checking contraIndications:', checkDuplicates(contraIndications));
console.log('Checking activeIngredients:', checkDuplicates(activeIngredients));
console.log('Checking drugCategories:', checkDuplicates(drugCategories.map((cat) => cat.name)));
console.log('Checking drugDosages:', checkDuplicates(drugDosages));
console.log('Checking countries:', checkDuplicates(countries));
