export const drugForms = [
	'AEROSOL',
	'BALM',
	'CAPSULE',
	'CREAM',
	'ELIXIR',
	'EMULSION',
	'FOAM',
	'GEL',
	'INHALANT',
	'INJECTION',
	'LIQUID',
	'LOTION',
	'MASK',
	'OIL',
	'OINTMENT',
	'PATCH',
	'PILL',
	'POWDER',
	'SERUM',
	'SOLUTION',
	'SPRAY',
	'SUPPOSITORY',
	'SUSPENSION',
	'SYRUP',
	'TABLET',
	'TINCTURE',
	'TOOTHPASTE',
	'MOUTHWASH',
	'SKIN_CARE',
	'COSMETIC',
	'SHAMPOO'
];

// done
export const indications = [
	'Pain',
	'Fever',
	'Inflammation',
	'Migraine',
	'Stroke',
	'Heartburn',
	'Nausea',
	'Cough',
	'Cold',
	'Flu',
	'Diarrhea',
	'Constipation',
	'Allergy',
	'Rash',
	'Headache',
	'Dizziness',
	'Fatigue',
	'Insomnia',
	'Anxiety',
	'Depression',
	'Arthritis',
	'Diabetes',
	'Hypertension',
	'Asthma',
	'Bronchitis',
	'Pneumonia',
	'Cancer',
	'Ulcer',
	'Gastritis',
	'Hemorrhoids',
	'Acne',
	'Angina',
	'Anemia',
	'Anorexia',
	'Arrhythmia',
	'Atherosclerosis',
	'Backache',
	'Bleeding',
	'Blisters',
	'Burns',
	'Cholesterol',
	'Colitis',
	'Conjunctivitis',
	'Cramps',
	'Dermatitis',
	'Dyspepsia',
	'Eczema',
	'Edema',
	'Emphysema',
	'Epilepsy',
	'Fibromyalgia',
	'Flatulence',
	'Glaucoma',
	'Gout',
	'Herpes',
	'Hyperthyroidism',
	'Hypothyroidism',
	'Impotence',
	'Infection',
	'Influenza',
	'Itching',
	'Jaundice',
	'Leukemia',
	'Lymphoma',
	'Malaria',
	'Menopause',
	'Menstruation',
	'Myalgia',
	'Neuralgia',
	'Obesity',
	'Osteoporosis',
	'Palpitations',
	'Pancreatitis',
	'Psoriasis',
	'Scabies',
	'Sinusitis',
	'Sneezing',
	'Spasms',
	'Swelling',
	'Syphilis',
	'Tetanus',
	'Thrombosis',
	'Tinnitus',
	'Tuberculosis',
	'Ulceration',
	'Vomiting',
	'Warts',
	'Wheezing',
	'Yeast'
];

export const _drugDosages = [
	'50 mg',
	'100 mg',
	'200 mg',
	'250 mg',
	'500 mg',
	'750 mg',
	'1 g',
	'5 mg',
	'10 mg',
	'20 mg',
	'25 mg',
	'30 mg',
	'40 mg',
	'75 mg',
	'150 mg',
	'300 mg',
	'400 mg',
	'600 mg',
	'1.5 g',
	'2 g'
];

// done
export const contraIndications = [
	'Allergy',
	'Pregnancy',
	'Lactation',
	'Hypersensitivity',
	'Anemia',
	'Asthma',
	'Bleeding',
	'Breastfeeding',
	'Cancer',
	'Cardiomyopathy',
	'Cirrhosis',
	'Colitis',
	'Coma',
	'Dehydration',
	'Depression',
	'Diabetes',
	'Diarrhea',
	'Emphysema',
	'Epilepsy',
	'Glaucoma',
	'Gout',
	'Hepatitis',
	'Hypertension',
	'Hypotension',
	'Hyperthyroidism',
	'Hypothyroidism',
	'Infection',
	'Inflammation',
	'Jaundice',
	'Kidney',
	'Liver',
	'Malnutrition',
	'Menopause',
	'Menstruation',
	'Migraine',
	'Myocarditis',
	'Obesity',
	'Osteoporosis',
	'Pancreatitis',
	'Parkinson',
	'Peptic',
	'Pregnancy',
	'Psychosis',
	'Seizures',
	'Shock',
	'Stomach',
	'Stroke',
	'Surgery',
	'Thrombosis',
	'Tuberculosis',
	'Ulcer',
	'Vertigo',
	'Vomiting'
];

export const activeIngredients = [
	'Aspirin',
	'Ibuprofen',
	'Paracetamol',
	'Amoxicillin',
	'Metformin',
	'Atorvastatin',
	'Omeprazole',
	'Lisinopril',
	'Simvastatin',
	'Levothyroxine',
	'Amlodipine',
	'Metoprolol',
	'Hydrochlorothiazide',
	'Losartan',
	'Gabapentin',
	'Citalopram',
	'Albuterol',
	'Prednisone',
	'Acetaminophen',
	'Ciprofloxacin',
	'Clindamycin',
	'Doxycycline',
	'Furosemide',
	'Glyburide',
	'Hydrocodone',
	'Hydroxychloroquine',
	'Indomethacin',
	'Loratadine',
	'Meloxicam',
	'Methotrexate',
	'Metronidazole',
	'Montelukast',
	'Naproxen',
	'Nifedipine',
	'Ondansetron',
	'Oxycodone',
	'Pantoprazole',
	'Prednisolone',
	'Ranitidine',
	'Sertraline',
	'Sildenafil',
	'Spironolactone',
	'Sumatriptan',
	'Tamsulosin',
	'Tetracycline',
	'Tramadol',
	'Trimethoprim',
	'Valsartan',
	'Venlafaxine',
	'Warfarin',
	'Zolpidem',
	'Acetazolamide',
	'Alendronate',
	'Allopurinol',
	'Azithromycin',
	'Bisoprolol',
	'Budesonide',
	'Carbamazepine',
	'Cefalexin',
	'Cetirizine',
	'Chlorphenamine',
	'Chlorpromazine',
	'Clopidogrel',
	'Codeine',
	'Cyclobenzaprine',
	'Dexamethasone',
	'Diazepam',
	'Digoxin',
	'Diphenhydramine',
	'Duloxetine',
	'Enalapril',
	'Esomeprazole',
	'Fluconazole',
	'Fluoxetine',
	'Folic',
	'Furosemide',
	'Gemfibrozil',
	'Glipizide',
	'Glyburide',
	'Haloperidol',
	'Hydralazine',
	'Hydromorphone',
	'Hydroxyzine',
	'Isosorbide',
	'Ketoconazole',
	'Labetalol',
	'Lamotrigine',
	'Levofloxacin',
	'Lidocaine',
	'Lithium',
	'Loperamide',
	'Methocarbamol',
	'Methylprednisolone',
	'Minocycline',
	'Mirtazapine',
	'Nalbuphine',
	'Nitrofurantoin',
	'Nitroglycerin',
	'Nortriptyline',
	'Olanzapine',
	'Oxcarbazepine',
	'Phenobarbital',
	'Phenytoin',
	'Pioglitazone',
	'Prazosin',
	'Propranolol',
	'Risperidone',
	'Scopolamine',
	'Tizanidine',
	'Tolterodine',
	'Topiramate',
	'Valproate',
	'Verapamil'
];

export const _drugCategories = [
	'Analgesic',
	'Antibiotic',
	'Antifungal',
	'Antiviral',
	'Antipyretic',
	'Antiseptic',
	'Antidepressant',
	'Antipsychotic',
	'Anticonvulsant',
	'Antihistamine',
	'Antihypertensive',
	'Anti-inflammatory',
	'Anticoagulant',
	'Antiemetic',
	'Antidiabetic',
	'Bronchodilator',
	'Decongestant',
	'Expectorant',
	'Diuretic',
	'Laxative',
	'Sedative',
	'Hypnotic',
	'Stimulant',
	'Anesthetic',
	'Antacid',
	'Antilipemic',
	'Immunosuppressant',
	'Muscle',
	'Relaxant',
	'Antirheumatic',
	'Corticosteroid',
	'Hormone',
	'Antimalarial',
	'Antiparasitic',
	'Antitussive',
	'Cardiovascular',
	'Dermatological',
	'Gastrointestinal',
	'Neurological',
	'Respiratory',
	'Ophthalmic',
	'Otic',
	'Thyroid',
	'Contraceptive',
	'Urological',
	'Nutritional',
	'Analgesics',
	'Antimicrobial',
	'Endocrine',
	'Enzyme',
	'Antineoplastic',
	'Vaccine',
	'Antivertigo',
	'Vasodilator',
	'Chelating',
	'Lithium',
	'Beta',
	'Calcium',
	'Opioid',
	'Statin',
	'ACE',
	'Angiotensin',
	'Antigout',
	'Antihyperlipidemic',
	'Antithrombotic',
	'Antiviral',
	'Antipsychotic',
	'Biologic',
	'Bisphosphonate',
	'Carbonic',
	'Hormonal',
	'Leukotriene',
	'Macrolide',
	'Nonsteroidal',
	'Nitrate',
	'Proton',
	'Retinoid',
	'Selective',
	'Sulfonylurea',
	'Thiazide',
	'Tetracycline',
	'Tricyclic',
	'Vasopressor'
];

// done
export const drugCategories = [
	{ name: 'Analgesic', description: 'Used to relieve pain.' },
	{ name: 'Antibiotic', description: 'Used to treat bacterial infections.' },
	{ name: 'Antifungal', description: 'Used to treat fungal infections.' },
	{ name: 'Antiviral', description: 'Used to treat viral infections.' },
	{ name: 'Antipyretic', description: 'Used to reduce fever.' },
	{ name: 'Antiseptic', description: 'Used to prevent infection in wounds.' },
	{ name: 'Antidepressant', description: 'Used to treat depression.' },
	{ name: 'Antipsychotic', description: 'Used to manage psychosis, including schizophrenia.' },
	{ name: 'Anticonvulsant', description: 'Used to prevent seizures.' },
	{ name: 'Antihistamine', description: 'Used to relieve allergy symptoms.' },
	{ name: 'Antihypertensive', description: 'Used to lower high blood pressure.' },
	{ name: 'Anti-inflammatory', description: 'Used to reduce inflammation.' },
	{ name: 'Anticoagulant', description: 'Used to prevent blood clots.' },
	{ name: 'Antiemetic', description: 'Used to prevent nausea and vomiting.' },
	{ name: 'Antidiabetic', description: 'Used to manage diabetes.' },
	{ name: 'Bronchodilator', description: 'Used to open the airways in the lungs.' },
	{ name: 'Decongestant', description: 'Used to relieve nasal congestion.' },
	{ name: 'Expectorant', description: 'Used to clear mucus from the airways.' },
	{ name: 'Diuretic', description: 'Used to remove excess fluid from the body.' },
	{ name: 'Laxative', description: 'Used to relieve constipation.' },
	{ name: 'Sedative', description: 'Used to promote calm or sleep.' },
	{ name: 'Hypnotic', description: 'Used to induce sleep.' },
	{ name: 'Stimulant', description: 'Used to increase alertness and energy.' },
	{ name: 'Anesthetic', description: 'Used to induce anesthesia.' },
	{ name: 'Antacid', description: 'Used to neutralize stomach acid.' },
	{ name: 'Antilipemic', description: 'Used to lower lipid levels in the blood.' },
	{ name: 'Immunosuppressant', description: 'Used to suppress the immune system.' },
	{ name: 'Muscle Relaxant', description: 'Used to relieve muscle spasms.' },
	{ name: 'Antirheumatic', description: 'Used to treat rheumatoid arthritis.' },
	{
		name: 'Corticosteroid',
		description: 'Used to reduce inflammation and suppress the immune system.'
	},
	{ name: 'Hormone', description: 'Used to supplement or replace hormones in the body.' },
	{ name: 'Antimalarial', description: 'Used to prevent or treat malaria.' },
	{ name: 'Antiparasitic', description: 'Used to treat parasitic infections.' },
	{ name: 'Antitussive', description: 'Used to suppress coughing.' },
	{ name: 'Cardiovascular', description: 'Used to treat heart and blood vessel conditions.' },
	{ name: 'Dermatological', description: 'Used to treat skin conditions.' },
	{ name: 'Gastrointestinal', description: 'Used to treat digestive system conditions.' },
	{ name: 'Neurological', description: 'Used to treat nervous system conditions.' },
	{ name: 'Respiratory', description: 'Used to treat respiratory system conditions.' },
	{ name: 'Ophthalmic', description: 'Used to treat eye conditions.' },
	{ name: 'Otic', description: 'Used to treat ear conditions.' },
	{ name: 'Thyroid', description: 'Used to treat thyroid conditions.' },
	{ name: 'Contraceptive', description: 'Used to prevent pregnancy.' },
	{ name: 'Urological', description: 'Used to treat urinary system conditions.' },
	{ name: 'Nutritional', description: 'Used to provide nutrients.' },
	{ name: 'Analgesics', description: 'Used to relieve pain.' },
	{ name: 'Antimicrobial', description: 'Used to kill or inhibit the growth of microorganisms.' },
	{ name: 'Endocrine', description: 'Used to treat hormonal imbalances.' },
	{ name: 'Enzyme', description: 'Used to replace or supplement enzymes.' },
	{ name: 'Antineoplastic', description: 'Used to treat cancer.' },
	{ name: 'Vaccine', description: 'Used to prevent infectious diseases.' },
	{ name: 'Antivertigo', description: 'Used to treat dizziness and vertigo.' },
	{ name: 'Vasodilator', description: 'Used to widen blood vessels.' },
	{ name: 'Chelating', description: 'Used to remove heavy metals from the body.' },
	{ name: 'Lithium', description: 'Used to treat bipolar disorder.' },
	{
		name: 'Beta Blocker',
		description: 'Used to manage abnormal heart rhythms and protect the heart.'
	},
	{ name: 'Calcium Channel Blocker', description: 'Used to lower blood pressure.' },
	{ name: 'Opioid', description: 'Used to relieve severe pain.' },
	{ name: 'Statin', description: 'Used to lower cholesterol levels.' },
	{ name: 'ACE Inhibitor', description: 'Used to lower blood pressure.' },
	{ name: 'Angiotensin Receptor Blocker', description: 'Used to lower blood pressure.' },
	{ name: 'Antigout', description: 'Used to treat gout.' },
	{ name: 'Antihyperlipidemic', description: 'Used to lower lipid levels in the blood.' },
	{ name: 'Antithrombotic', description: 'Used to reduce the formation of blood clots.' },
	{ name: 'Antiviral', description: 'Used to treat viral infections.' },
	{ name: 'Antipsychotic', description: 'Used to manage psychosis, including schizophrenia.' },
	{
		name: 'Biologic',
		description: 'Used to treat various medical conditions through biological methods.'
	},
	{ name: 'Bisphosphonate', description: 'Used to prevent the loss of bone density.' },
	{ name: 'Carbonic Anhydrase Inhibitor', description: 'Used to reduce fluid buildup.' },
	{ name: 'Hormonal', description: 'Used to manage hormonal imbalances.' },
	{ name: 'Leukotriene Receptor Antagonist', description: 'Used to manage allergies and asthma.' },
	{ name: 'Macrolide', description: 'Used to treat bacterial infections.' },
	{ name: 'Nonsteroidal Anti-inflammatory', description: 'Used to reduce pain and inflammation.' },
	{ name: 'Nitrate', description: 'Used to manage chest pain.' },
	{ name: 'Proton Pump Inhibitor', description: 'Used to reduce stomach acid.' },
	{ name: 'Retinoid', description: 'Used to treat skin conditions.' },
	{
		name: 'Selective Serotonin Reuptake Inhibitor',
		description: 'Used to treat depression and anxiety.'
	},
	{ name: 'Sulfonylurea', description: 'Used to manage type 2 diabetes.' },
	{ name: 'Thiazide Diuretic', description: 'Used to treat high blood pressure.' },
	{ name: 'Tetracycline', description: 'Used to treat bacterial infections.' },
	{ name: 'Tricyclic Antidepressant', description: 'Used to treat depression.' },
	{ name: 'Vasopressor', description: 'Used to raise blood pressure.' }
];

// done
export const drugDosages: {
	amount: number;
	unit: 'mg' | 'g' | 'l' | 'ml' | 'unit';
	per: number;
	perUnit: 'mg' | 'g' | 'l' | 'ml' | 'unit';
}[] = [
	{ amount: 50, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 100, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 200, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 250, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 500, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 750, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 5, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 10, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 20, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 25, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 30, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 40, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 75, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 150, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 300, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 400, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 600, unit: 'mg', per: 1, perUnit: 'unit' },
	{ amount: 1.5, unit: 'g', per: 1, perUnit: 'unit' },
	{ amount: 2, unit: 'g', per: 1, perUnit: 'unit' }
];
